version: '3.8'

services:
  db:
    image: postgres
    container_name: goPSQL
    environment:
      POSTGRES_DB: "newdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    # volumes:
    #   - .:/docker-entrypoint-initdb.d
    ports:
      - "5438:5432"
    networks:
      - postnet
  app:
    build: ../basic-auth-sys
    ports:
     - 4000:4000
    depends_on:
     - db
    environment:
     - PGUSER=${PGUSER:-postgres}
     - PGPASSWORD=${PGPASSWORD:-password}
     - PGHOST=${PGHOST:-db}
     - PGPORT=${PGPORT:-5432}
     - PGDATABASE=${PGDATABASE-newdb}
    networks:
      - postnet
networks:
  postnet:
    name: postnet
    external: true
volumes:
  pgdata:
